import {APP_VERSION,KEYS,CATEGORIES,SONGS,DRILLS,DRILL_BY_ID,REFERENCES,REFERENCE_BY_ID,makeSession} from './data.js';
import {buildExample,renderTabSvg,renderFretboardSvg,shellShapes,chordDiagramSvg,progressionFor,escapeHtml as e,pitchName,keyPc,INTERVALS,buildNotePath} from './music.js';
import {loadState,saveState,addRecord,weeklyReport,downloadText,exportCsv,importedSnapshot,CloudSync} from './storage.js';
const state=loadState();
if(!state.cloud?.url&&window.GPL_CONFIG?.supabaseUrl){state.cloud={url:window.GPL_CONFIG.supabaseUrl,key:window.GPL_CONFIG.supabaseKey};saveState(state);}
document.body.dataset.theme=state.settings.theme;
let showRating=false,diagramStep=-1,cloudMessage='Local only · records saved in this browser',cloudKind='info';let toastTimeout=0;
const $=id=>document.getElementById(id);
const safe=(s)=>e(s??'');
const categoryTitle=cat=>CATEGORIES.find(c=>c[0]===cat)?.[1]||cat;
const iconPaths={home:'<path d="m3 11 9-8 9 8v9a1 1 0 0 1-1 1h-5v-6H9v6H4a1 1 0 0 1-1-1z"/>',play:'<path d="m8 5 11 7-11 7z"/>',pause:'<rect x="6" y="5" width="4" height="14"/><rect x="14" y="5" width="4" height="14"/>',music:'<path d="M9 18V5l12-2v13"/><circle cx="6" cy="18" r="3"/><circle cx="18" cy="16" r="3"/>',library:'<path d="M4 5h5v16H4zM10 3h5v18h-5zM16 7h4v14h-4z"/>',book:'<path d="M12 7c-3-2-6-2-10-1v14c4-1 7-1 10 1 3-2 6-2 10-1V6c-4-1-7-1-10 1zM12 7v14"/>',chart:'<path d="M4 20V10h4v10zM10 20V4h4v16zM16 20v-7h4v7z"/>',settings:'<circle cx="12" cy="12" r="3"/><path d="M12 2v3M12 19v3M2 12h3M19 12h3M5 5l2 2M17 17l2 2M19 5l-2 2M7 17l-2 2"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 6v6l4 2"/>',arrow:'<path d="M5 12h14m-6-6 6 6-6 6"/>',check:'<path d="m4 12 5 5L20 6"/>',chevron:'<path d="m9 18 6-6-6-6"/>',minus:'<path d="M5 12h14"/>',plus:'<path d="M12 5v14M5 12h14"/>',cloud:'<path d="M4 16a4 4 0 0 1 1-8 7 7 0 0 1 13 2 4 4 0 0 1 1 8H5"/>',download:'<path d="M12 3v12m-5-5 5 5 5-5M4 18v3h16v-3"/>',refresh:'<path d="M20 11a8 8 0 0 0-14-5L3 9m0-5v5h5M4 13a8 8 0 0 0 14 5l3-3m0 5v-5h-5"/>',headphones:'<path d="M3 15V12a9 9 0 0 1 18 0v3M3 15h5v6H5a2 2 0 0 1-2-2v-4zm18 0h-5v6h3a2 2 0 0 0 2-2v-4z"/>',target:'<circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="5"/><circle cx="12" cy="12" r="1"/>',upload:'<path d="M12 21V9m-5 5 5-5 5 5M4 6V3h16v3"/>',sun:'<circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M2 12h2M20 12h2M5 5l2 2M17 17l2 2M19 5l-2 2M7 17l-2 2"/>'};
const ic=(name)=>`<span class="icon" aria-hidden="true"><svg viewBox="0 0 24 24">${iconPaths[name]||iconPaths.target}</svg></span>`;
const btn=(action,label,cls='')=>`<button type="button" class="btn ${cls}" data-action="${action}">${label}</button>`;
const tag=(s,special=false)=>`<span class="pill${special?' special':''}">${safe(s)}</span>`;
const rect=(title,description,action)=>`<a class="list-row" href="${action}"><span class="row-main"><div class="row-title">${safe(title)}</div><div class="row-desc">${safe(description)}</div></span>${ic('chevron')}</a>`;
const nav=[['today','Today','home'],['practice','Practice','play'],['songs','Songs','music'],['drills','Drills','library'],['references','References','book'],['progress','Progress','chart']];
let currentHash='';
function route(){const parts=decodeURIComponent(location.hash.replace(/^#/,'')||'today').split('/');return {page:parts[0],id:parts.slice(1).join('/')};}
function setRoute(r){if(location.hash==='#'+r){render();return;}location.hash=r;}
function pageHeader(eyebrow,title,subtitle,right=''){return `<div class="page-head"><div><div class="eyebrow">${safe(eyebrow)}</div><h1>${safe(title)}</h1><p>${safe(subtitle)}</p></div>${right}</div>`;}
function countSessions(){return state.records.filter(r=>r.kind==='session'&&!r.payload?.isFree).length;}
function lastSeven(){const since=Date.now()-7*86400000;return state.records.filter(r=>Date.parse(r.created_at)>=since);}
function latestSong(songId){return state.records.filter(r=>r.kind==='song'&&r.payload?.songId===songId).sort((a,b)=>b.created_at.localeCompare(a.created_at))[0]?.payload;}
function todayKey(){return state.settings.selectedKey==='auto'?KEYS[countSessions()%KEYS.length]:state.settings.selectedKey;}
function showToast(msg){const el=$('toast');if(!el)return;clearTimeout(toastTimeout);el.textContent=msg;el.className='visible';toastTimeout=setTimeout(()=>{el.className='';},3200);}
const cloud=new CloudSync({state,onUpdate:()=>render(),onStatus:(m,k)=>{cloudMessage=m;cloudKind=k;const msg=$('cloud-status');if(msg){msg.textContent=m;msg.className='status '+k;}const side=$('sidebar-status');if(side){side.textContent=m;}}});
function shell(content){const r=route(),active=['today','practice','songs','drills','references','progress'].includes(r.page)?r.page:(r.page==='drill'?'drills':r.page==='song'?'songs':r.page==='reference'?'references':'today');
 const navHTML=nav.map(([href,text,icon])=>`<a href="#${href}" class="nav-item ${active===href?'active':''}" ${active===href?'aria-current="page"':''}><span class="nav-ic">${ic(icon)}</span>${text}</a>`).join('');
 return `<div class="shell"><aside class="sidebar"><a href="#today" class="brand route-link"><span class="brand-mark">${ic('music')}</span><div><div class="brand-title">Guitar Practice Lab</div><div class="brand-small">Music · Precision · Flow</div></div></a><nav class="nav" aria-label="Main navigation">${navHTML}</nav><div class="side-bottom"><div class="small"><span class="sync-pip ${cloud.user?'good':''}"></span>Practice data</div><p id="sidebar-status">${safe(cloudMessage)}</p><a href="#settings">${ic('settings')} &nbsp; Settings & cloud</a></div></aside><div class="main-wrap"><div class="topbar"><div><span class="eyebrow">Practice Workspace</span></div><div class="top-right">${state.active?tag('Session in progress',true):tag('Version '+APP_VERSION)}<a class="btn small ghost" href="#settings">${ic('settings')}<span class="desktop-only">Settings</span></a></div></div><main class="page" id="main-content">${content}</main></div></div>`;
}
function render(){document.body.dataset.theme=state.settings.theme;const r=route();let html='';
 switch(r.page){case 'today':html=renderToday();break;case 'practice':html=renderPractice();break;case 'drills':html=renderDrills();break;case 'drill':html=renderDrillDetail(r.id);break;case 'songs':html=renderSongs();break;case 'song':html=renderSongDetail(r.id);break;case 'references':html=renderReferences();break;case 'reference':html=renderReferenceDetail(r.id);break;case 'progress':html=renderProgress();break;case 'settings':html=renderSettings();break;default:html=renderToday();}
 $('app').innerHTML=shell(html);updateClock();}
function queueOverview(s){return `<div class="list">${s.entries.map((entry,i)=>{const d=DRILL_BY_ID[entry.id];return `<div class="step-row ${entry.done?'done':''}"><div class="step-n">${entry.done?'✓':i+1}</div><div class="step-info"><div class="step-name">${safe(d?.title||'Song practice')}</div><div class="step-min">${safe(d?.category?categoryTitle(d.category):'Repertoire')} · ${entry.minutes} min</div></div><span class="small muted">${entry.minutes}:00</span></div>`;}).join('')}</div>`;}
function renderToday(){const complete=countSessions(),recent=lastSeven(),sessions=recent.filter(r=>r.kind==='session'),minutes=sessions.reduce((x,s)=>x+(Number(s.payload?.durationMinutes)||0),0),clean=recent.filter(r=>r.kind==='drill'&&r.payload?.rating==='clean').length;
 const mode=state.settings.selectedMode,preview=makeSession(complete,mode,state.settings.selectedSong);if(state.settings.selectedKey!=='auto')preview.key=state.settings.selectedKey;
 const top=state.active?`<section class="hero"><div class="eyebrow">Resume where you left off</div><h2>Session in progress · ${safe(state.active.key)}</h2><p>Your current drill and logging are saved locally on this device.</p><div class="buttons">${btn('resume-session',`${ic('play')} Resume practice`,'primary')}</div></section>`:`<section class="hero"><div class="eyebrow">Focused practice · No distractions</div><h2>${mode==='repertoire'?'Technique meets your setlist':'Build fluency, one phrase at a time.'}</h2><p>45 minutes of picking control, muting, musical arpeggios, jazz voice leading, comping and ear training. Your next key is <strong>${safe(preview.key)}</strong>.</p><div class="buttons">${btn('start-session',`${ic('play')} Start 45-minute session`,'primary')}${tag('Day '+(complete+1)+' · '+(mode==='technique'?'Technique':'Repertoire'))}</div></section>`;
 return `${pageHeader('Home','Ready to practise?','A consistent system for technique, jazz language and live repertoire.')}
 <div class="metrics"><div class="metric"><div class="label">Sessions · last 7 days</div><div class="number">${sessions.length}</div></div><div class="metric"><div class="label">Minutes · last 7 days</div><div class="number">${minutes}</div></div><div class="metric"><div class="label">Clean drill ratings</div><div class="number">${clean}</div></div></div>
 <div class="grid-main"><div>${top}<div style="height:20px"></div><div class="card"><div class="card-header"><h2>Today's 45-minute plan</h2>${tag('Key '+preview.key,true)}</div>${queueOverview(state.active||preview)}</div></div>
 <aside class="card"><div class="card-header"><h3>Session setup</h3>${ic('target')}</div><div class="form-group"><label for="mode">Practice mode</label><select id="mode" data-setting="selectedMode" ${state.active?'disabled':''}><option value="technique" ${mode==='technique'?'selected':''}>Technique day</option><option value="repertoire" ${mode==='repertoire'?'selected':''}>Repertoire day</option></select></div><div class="form-group" style="margin-top:13px"><label for="key">Primary key</label><select id="key" data-setting="selectedKey" ${state.active?'disabled':''}><option value="auto" ${state.settings.selectedKey==='auto'?'selected':''}>Auto · circle of fourths</option>${KEYS.map(k=>`<option value="${k}" ${state.settings.selectedKey===k?'selected':''}>${k}</option>`).join('')}</select></div><div class="form-group" style="margin-top:13px"><label for="song">Repertoire focus</label><select id="song" data-setting="selectedSong" ${state.active?'disabled':''}>${SONGS.map(s=>`<option value="${s.id}" ${state.settings.selectedSong===s.id?'selected':''}>${safe(s.title)}</option>`).join('')}</select></div><div class="divider"></div><div class="eyebrow">Key rotation</div><div class="key-grid" style="margin-top:12px">${KEYS.map((k,i)=>`<div class="key-tile ${preview.key===k?'current':''}">${k.replace('b','♭')}</div>`).join('')}</div><p class="footnote">One primary key per practice day. A full rotation takes 12 sessions; override the key when needed.</p></aside></div>`;
}
function progressSvg(notes){return `<div class="diagram-viewport" id="diagram-container">${state.settings.diagram==='fretboard'?renderFretboardSvg(notes,diagramStep,state.settings.labels):renderTabSvg(notes,diagramStep)}</div>`;}
function chordBlocks(key){return `<div class="grid-2">${shellShapes(key).map(c=>`<div style="background:var(--panel2);padding:12px;border-radius:12px;min-width:0"><div class="small muted">${c.label}</div><h3>${safe(c.name)}</h3><div class="diagram-viewport" style="padding:0;min-height:0;border:0">${chordDiagramSvg(c)}</div></div>`).join('')}</div><p class="footnote">These are transposable shell-voicing examples. Some keys use higher positions; choose a comfortable octave and mute each X string.</p>`;}
function progressionPills(key){return `<div class="buttons">${progressionFor(key).map(p=>`<span class="pill special">${p.role} · ${safe(p.name)}</span>`).join('')}</div>`;}
function clockMs(){const a=state.active;if(!a)return 0;return Math.max(0,(a.elapsedMs||0)+(a.startedAt?Date.now()-a.startedAt:0));}
function formatSeconds(seconds){seconds=Math.max(0,Math.floor(seconds));return String(Math.floor(seconds/60)).padStart(2,'0')+':'+String(seconds%60).padStart(2,'0');}
function updateClock(){const a=state.active,clock=$('practice-clock'),bar=$('time-bar');if(!a||!clock)return;const item=a.entries[a.position];if(!item)return;const used=clockMs()/1000,planned=item.minutes*60;clock.textContent=formatSeconds(Math.max(0,planned-used));if(bar)bar.style.width=Math.min(100,used/planned*100)+'%';const running=$('timer-running');if(running)running.textContent=a.startedAt?'Pause timer':'Start timer';}
function currentDrill(){const a=state.active;return a?.entries?.[a.position]||null;}
function renderPractice(){if(!state.active)return `${pageHeader('Practice','Active workspace','Start a session to display your musical drills and timer.')}
 <div class="card empty">No active session. Choose a 45-minute plan on Today, or open a single drill from the library.<div class="buttons" style="justify-content:center;margin-top:16px"><a href="#today" class="btn primary">Choose a session</a><a href="#drills" class="btn">Browse drills</a></div></div>`;
 const a=state.active,entry=currentDrill();if(!entry)return renderEndSession();const d=DRILL_BY_ID[entry.id],isSong=entry.id==='song',song=SONGS.find(s=>s.id===a.songId)||SONGS[0];const time=Math.max(0,Math.ceil(entry.minutes*60-clockMs()/1000));const isChords=d?.kind==='chords',isMusical=['ii-v-i','enclosure','approach'].includes(d?.kind);
 const notes=d?buildExample(d.kind,a.key,d.quality||'maj7',d.octaves||2,state.settings.position):[];
 const diagram=!isSong&&!isChords&&!notes.length?`<div class="alert">This exact range does not fit a 22-fret standard-tuned guitar in ${safe(a.key)}. Choose a different key or use a two-octave drill.</div>`:isSong?`<div class="callout"><strong>${safe(song.title)}</strong><p>${safe(song.focus)}</p><p>${safe(song.notes)}</p></div>`:isChords?chordBlocks(a.key):`${progressSvg(notes)}<div class="color-legend" style="margin-top:10px"><span><span class="dot root"></span>Root/first note</span><span><span class="dot"></span>Chord tone</span><span><span class="dot active"></span>Selected note</span></div>`;
 const previewTime=`<div class="control-panel"><div style="flex:1;min-width:120px"><div class="eyebrow">Tempo</div><div class="tempo"><span id="current-bpm">${state.settings.defaultBpm}</span><span class="muted" style="font-size:14px"> BPM</span></div></div><div style="text-align:right"><div class="eyebrow">Remaining</div><div class="timer" id="practice-clock">${formatSeconds(time)}</div></div></div><div class="meter" style="margin:13px 0 18px"><div id="time-bar" style="width:${Math.min(100,clockMs()/(entry.minutes*600)*100)}%"></div></div>
 <div class="buttons">${btn('tempo-down',`${ic('minus')} 5 BPM`)}${btn('toggle-timer',`<span id="timer-running">${a.startedAt?'Pause timer':'Start timer'}</span>`,'primary')}${btn('tempo-up',`${ic('plus')} 5 BPM`)}${btn('metro-toggle',`${ic('headphones')} <span id="metro-label">${metronome.playing?'Stop click':'Metronome'}</span>`)} </div><div class="form-row" style="margin-top:14px"><div class="form-group"><label>Subdivision</label><select data-setting="subdivision"><option value="quarter" ${state.settings.subdivision==='quarter'?'selected':''}>Quarter-note pulse</option><option value="swing" ${state.settings.subdivision==='swing'?'selected':''}>Swung eighths</option><option value="triplet" ${state.settings.subdivision==='triplet'?'selected':''}>Triplets</option></select></div><div class="form-group"><label>Meter</label><select data-setting="meter"><option value="4/4" ${state.settings.meter==='4/4'?'selected':''}>4/4</option><option value="6/8" ${state.settings.meter==='6/8'?'selected':''}>6/8 (2 dotted-quarter pulses)</option></select></div></div>`;
 const stepLabel=isSong?song.title:d.title;
 const instruct=isSong?['Select one difficult section, not the entire arrangement.','Play once under tempo, then at performance tempo.','Record what specifically needs work for the next session.']:d.instructions;
 const positionControl=(!isSong&&['arpeggio','scale'].includes(d?.kind))?`<div class="form-group" style="max-width:280px;margin:12px 0"><label>Fretboard area (suggested route)</label><select data-setting="position"><option value="low" ${state.settings.position==='low'?'selected':''}>Lower neck</option><option value="mid" ${state.settings.position==='mid'?'selected':''}>Middle neck</option><option value="high" ${state.settings.position==='high'?'selected':''}>Upper neck</option></select></div>`:'';
 const noteControls=isChords||isSong?'':`<div class="buttons" style="margin-top:10px">${btn('step-prev',`${ic('minus')} Previous note`,'small')}${tag(diagramStep>=0?`Note ${diagramStep+1} of ${notes.length}`:'All notes')}${btn('step-next',`Next note ${ic('arrow')}`,'small')}<div style="flex:1"></div><div class="segmented"><button class="${state.settings.diagram==='tab'?'active':''}" data-action="diagram-tab">TAB</button><button class="${state.settings.diagram==='fretboard'?'active':''}" data-action="diagram-fretboard">Fretboard</button></div></div><div class="buttons" style="margin-top:8px">${btn('labels-note','Notes','small')}${btn('labels-interval','Intervals','small')}${btn('labels-hidden','Hide labels','small')}</div>`;
 const refs=(d?.reference||[]).map(id=>`<a href="#reference/${id}">${safe(REFERENCE_BY_ID[id]?.title||id)}</a>`).join('');
 return `${pageHeader('Active session',stepLabel,`Day ${a.dayNumber+1} · ${a.key.replace('b','♭')} · ${a.mode==='technique'?'Technique':'Repertoire'} · ${entry.minutes} min`,tag((a.position+1)+' / '+a.entries.length,true))}
 <div class="grid-main"><div><div class="card"><div class="card-header"><div><div class="eyebrow">${safe(isSong?'Performance rehearsal':categoryTitle(d.category))}</div><h2 style="margin-top:8px">${safe(isSong?song.focus:d.summary)}</h2></div>${ic('target')}</div>${isMusical?`${progressionPills(a.key)}<div style="height:12px"></div>`:''}${diagram}${positionControl}${noteControls}</div>
 <div class="card" style="margin-top:17px"><div class="card-header"><h2>Timing & metronome</h2>${tag('Jazz III / Jazz II')}</div>${previewTime}<div class="divider"></div>${showRating?`<div class="eyebrow">One-tap drill rating</div><p class="small muted">Save your best clean tempo and advance. Precision is self-assessed.</p><div class="rating-row">${[['clean','Clean','Controlled & relaxed'],['almost','Mostly clean','A few mistakes'],['retry','Needs work','Slow it down']].map(([id,title,txt])=>`<button class="btn" data-action="rate-${id}"><span class="rating-h">${title}</span><span class="rating-sm">${txt}</span></button>`).join('')}</div><div class="form-group" style="margin-top:14px"><label>Optional issue</label><select id="drill-issue"><option value="none">None</option><option value="muting">Unwanted string noise</option><option value="precision">Picking accuracy</option><option value="timing">Timing or swing feel</option><option value="tension">Excess tension</option><option value="fingering">Fretting / position change</option></select></div>${btn('rating-cancel','Continue practising','small ghost')}`:`<div class="buttons">${btn('rating-open',`${ic('check')} Finish & rate`,'primary')}${btn('skip-drill','Skip drill','ghost')}${btn('end-early','End session','quiet')}</div>`}</div></div>
 <aside><div class="card"><div class="card-header"><h3>Instructions</h3>${ic('book')}</div><ol class="instruction-list">${instruct.map(line=>`<li>${safe(line)}</li>`).join('')}</ol>${refs?`<div class="divider"></div><div class="eyebrow">Technique references</div><div class="chip-links">${refs}</div>`:''}${isSong?`<div class="divider"></div><a href="#song/${song.id}" class="btn full">Open song profile ${ic('arrow')}</a>`:''}</div><div class="card" style="margin-top:16px"><div class="card-header"><h3>Session route</h3>${tag(a.key,true)}</div>${a.entries.map((x,i)=>`<div class="step-row ${a.position===i?'selected':''} ${x.done?'done':''}" style="padding:10px 4px"><div class="step-n">${x.done?'✓':i+1}</div><div class="step-info"><div class="step-name">${safe(DRILL_BY_ID[x.id]?.title||(SONGS.find(s=>s.id===a.songId)?.title||'Song'))}</div><div class="step-min">${x.minutes} min</div></div></div>`).join('')}</div></aside></div>`;
}
function renderEndSession(){const a=state.active;const entries=a.entries;const done=entries.filter(x=>x.done).length;return `${pageHeader('Session recap','Session complete','Review what you practised and add one practical observation.')}
 <div class="grid-2"><div class="card"><div class="card-header"><h2>Completed drills</h2>${tag(`${done} of ${entries.length}`)}</div>${queueOverview(a)}<div class="divider"></div><label for="session-notes" class="small muted">What should you remember next time?</label><textarea id="session-notes" rows="4" placeholder="e.g. String skips are cleaner at 70 BPM, but B string still rings at 85.">${safe(a.notes||'')}</textarea><div class="buttons" style="margin-top:14px">${btn('save-session',`${ic('check')} Save session`,'primary')}${btn('resume-last','Return to drills','ghost')}</div></div><div class="card"><h2>Key of ${safe(a.key)}</h2><p>Entries were saved individually as you rated each drill. Saving this recap completes the day and advances your 12-key rotation.</p><div class="callout">Weekly exports include completed sessions, individual drill tempos, self-rated precision, recurring issues and session notes.</div></div></div>`;}
function renderDrills(){return `${pageHeader('Technique library','Musical drills','Choose an exercise, view its notation and start a focused practice session.',`${tag(DRILLS.length+' drills')}`)}
 <div class="search-wrap"><input class="field" id="drill-search" placeholder="Search arpeggios, muting, chromaticism…" aria-label="Search drills"/><select id="drill-category" aria-label="Filter category"><option value="all">All categories</option>${CATEGORIES.map(c=>`<option value="${c[0]}">${c[1]}</option>`).join('')}</select></div>
 <div class="list" id="drill-results">${DRILLS.map(d=>`<a class="list-row drill-search-row" data-category="${d.category}" data-search="${safe((d.title+' '+d.summary+' '+d.category).toLowerCase())}" href="#drill/${d.id}"><div class="row-main"><div class="row-title">${safe(d.title)}</div><div class="row-desc">${safe(d.summary)}</div></div><span class="badge">${d.minutes} min</span>${ic('chevron')}</a>`).join('')}</div>`;}
function renderDrillDetail(id){const d=DRILL_BY_ID[id];if(!d)return `${pageHeader('Library','Drill not found','Return to the library.')}`;
 const key=todayKey(),notes=buildExample(d.kind,key,d.quality||'maj7',d.octaves||2,state.settings.position),rec=(d.reference||[]).map(ref=>REFERENCE_BY_ID[ref]).filter(Boolean),isChord=d.kind==='chords';
 return `${pageHeader(categoryTitle(d.category),d.title,d.summary,btn(`start-free:${d.id}`,`${ic('play')} Practise this drill`,'primary'))}
 <div class="grid-main"><div class="card"><div class="card-header"><h2>Exercise diagram</h2>${tag(key,true)}</div>${isChord?chordBlocks(key):!notes.length?`<div class="alert">A full three-octave path is not available in this key on a 22-fret standard-tuned guitar. Try another key or a two-octave arpeggio.</div>`:`<div class="eyebrow">Tab · D = down, U = up</div><div class="diagram-viewport" style="margin-top:10px">${renderTabSvg(notes)}</div><div class="eyebrow" style="margin-top:20px">Fretboard</div><div class="diagram-viewport" style="margin-top:10px">${renderFretboardSvg(notes,-1,'note')}</div>`}${d.octaves===3?`<p class="alert">Three-octave lines can reach very high frets in some keys. Reduce the range or change key if your guitar or neck comfort makes this impractical.</p>`:''}<div class="divider"></div><h3>How to practise</h3><ol class="instruction-list">${d.instructions.map(i=>`<li>${safe(i)}</li>`).join('')}</ol></div><aside class="card"><h3>References</h3>${rec.map(r=>rect(r.title,r.takeaway,'#reference/'+r.id)).join('')||'<p>No specific reference linked.</p>'}<div class="divider"></div><div class="buttons">${btn(`start-free:${d.id}`,'Start solo practice','primary full')}<a class="btn full ghost" href="#drills">Back to library</a></div></aside></div>`;
}
function renderSongs(){const logged=state.records.filter(r=>r.kind==='song');return `${pageHeader('Performance repertoire','Songs & setlists','Your Logos-Motive setlist, with rehearsal priorities and performance notes.',tag(SONGS.length+' songs'))}
 <div class="grid-main"><div class="list">${SONGS.map((s,i)=>{const last=latestSong(s.id);return `<a class="song-item" href="#song/${s.id}"><div class="song-n">${String(i+1).padStart(2,'0')}</div><div class="song-copy"><div class="song-title">${safe(s.title)}</div><p>${safe(s.focus)}</p></div><span class="badge">${last?safe(last.readiness||'Tracking'):'Not tracked'}</span>${ic('chevron')}</a>`;}).join('')}</div><aside class="card"><div class="eyebrow">Repertoire tracking</div><h2 style="margin-top:12px">From drill to performance</h2><p>Give each song a working key, tempo and readiness status. Keep a short note about the next musical problem to solve.</p><div class="divider"></div><div class="metric"><div class="label">Songs with rehearsal logs</div><div class="number">${new Set(logged.map(r=>r.payload?.songId)).size} / ${SONGS.length}</div></div><p class="footnote">Arrangements can use different keys, tempos and song structures. The app does not assume a recording's key is yours.</p></aside></div>`;}
function renderSongDetail(id){const song=SONGS.find(s=>s.id===id);if(!song)return `${pageHeader('Repertoire','Song not found','Choose a song from the list.')}`;const prev=latestSong(id)||{};
 const related=DRILL_BY_ID[song.suggested];const entries=state.records.filter(r=>r.kind==='song'&&r.payload?.songId===id).sort((a,b)=>b.created_at.localeCompare(a.created_at));
 return `${pageHeader('Repertoire · Logos-Motive',song.title,song.focus,btn(`song-focus:${id}`,`${ic('play')} Practise song · 12 min`,'primary'))}
 <div class="grid-main"><div class="card"><div class="card-header"><h2>Practice profile</h2>${tag(song.meter)}</div><div class="callout">${safe(song.notes)}</div><div class="form-row" style="margin-top:19px"><div class="form-group"><label for="song-key">Your arrangement key (optional)</label><input class="field" id="song-key" maxlength="12" value="${safe(prev.key||'')}" placeholder="e.g. G minor"/></div><div class="form-group"><label for="song-tempo">Target BPM (optional)</label><input class="field" id="song-tempo" inputmode="numeric" type="number" min="30" max="260" value="${safe(prev.tempo||'')}" placeholder="e.g. 65"/></div><div class="form-group"><label for="song-readiness">Performance readiness</label><select id="song-readiness">${[['learning','Learning'],['developing','Developing'],['ready','Performance ready'],['maintaining','Maintenance']].map(([v,label])=>`<option value="${v}" ${(prev.readiness||'learning')===v?'selected':''}>${label}</option>`).join('')}</select></div></div>
 <h3 style="margin-top:24px">Practised components</h3><div class="song-sections">${[['harmony','Harmony'],['picking','Picking / tone'],['solo','Melody / solo'],['structure','Structure / transitions'],['vocals','Vocal coordination']].map(([id,label])=>`<label><input type="checkbox" data-song-section="${id}" ${(prev.sections||[]).includes(id)?'checked':''}/> ${label}</label>`).join('')}</div>
 <div class="form-group" style="margin-top:19px"><label for="song-notes">What will you work on next?</label><textarea rows="5" id="song-notes" placeholder="A specific passage, transition, technique, or vocal/guitar coordination issue…">${safe(prev.notes||'')}</textarea></div><div class="buttons" style="margin-top:14px">${btn(`save-song:${id}`,`${ic('check')} Save rehearsal notes`,'primary')}<a class="btn ghost" href="#songs">All songs</a></div></div>
 <aside><div class="card"><h3>Connected technique</h3><a class="list-row" href="#drill/${related.id}"><div class="row-main"><div class="row-title">${safe(related.title)}</div><div class="row-desc">${safe(related.summary)}</div></div>${ic('chevron')}</a><div class="divider"></div><h3>Practice history</h3>${entries.length?entries.slice(0,6).map(r=>`<div class="step-row"><div class="step-info"><div class="step-name">${new Date(r.created_at).toLocaleDateString()}</div><div class="step-min">${safe(r.payload.readiness||'Logged')} · ${safe(r.payload.notes||'No note')}</div></div></div>`).join(''):'<p>No rehearsal entries recorded yet.</p>'}</div></aside></div>`;}
function renderReferences(){return `${pageHeader('Permanent handbook','References & technique','Original notes and diagrams linked directly to your active exercises.',tag(REFERENCES.length+' topics'))}
 <div class="cards">${REFERENCES.map(ref=>`<a class="card route-link" href="#reference/${ref.id}" style="display:block"><div class="eyebrow">${safe(ref.category)}</div><h2 style="margin-top:12px">${safe(ref.title)}</h2><p>${safe(ref.takeaway)}</p><div class="buttons" style="margin-top:12px;color:var(--teal);font-size:12px;font-weight:730">Open reference ${ic('arrow')}</div></a>`).join('')}</div>`;}
function renderReferenceDetail(id){const ref=REFERENCE_BY_ID[id];if(!ref)return `${pageHeader('Handbook','Reference not found','Return to the reference library.')}`;const relevant=DRILLS.filter(d=>(d.reference||[]).includes(id));return `${pageHeader(ref.category,ref.title,ref.takeaway)}<div class="grid-main"><div class="card"><h2>Essential ideas</h2><ol class="instruction-list">${ref.points.map(p=>`<li>${safe(p)}</li>`).join('')}</ol><div class="divider"></div><h3>Further learning</h3><div class="ref-links">${ref.links.map(([label,url])=>`<a href="${safe(url)}" target="_blank" rel="noopener noreferrer">${safe(label)} ↗</a>`).join('')||'<p class="small muted">Use the related drills to reinforce these concepts.</p>'}</div><div class="divider"></div><a href="#references" class="btn ghost">All references</a></div><aside class="card"><h3>Related exercises</h3><div class="list">${relevant.slice(0,9).map(d=>rect(d.title,d.summary,'#drill/'+d.id)).join('')}</div></aside></div>`;}
function renderProgress(){const history=[...state.records].sort((a,b)=>b.created_at.localeCompare(a.created_at)),sessions=history.filter(r=>r.kind==='session'),drills=history.filter(r=>r.kind==='drill'),songs=history.filter(r=>r.kind==='song');const issues={};const byDrill={};for(const r of drills){const p=r.payload||{};if(p.issue&&p.issue!=='none')issues[p.issue]=(issues[p.issue]||0)+1;if(p.rating==='clean'){const k=(p.drillId||'Unknown')+' · '+(p.key||'')+' · '+(p.subdivision||'quarter')+' · '+(p.position||'low');byDrill[k]=Math.max(byDrill[k]||0,Number(p.bpm)||0);}}
 const keys=Object.fromEntries(KEYS.map(k=>[k,0]));sessions.forEach(r=>{if(keys[r.payload?.key]!==undefined)keys[r.payload.key]++;});const bars=Object.entries(byDrill).sort((a,b)=>b[1]-a[1]).slice(0,7);const max=Math.max(120,...bars.map(b=>b[1]));
 return `${pageHeader('History & exports','Practice progress','A few meaningful measures, not a data science project.')}
 <div class="metrics"><div class="metric"><div class="label">Completed sessions</div><div class="number">${sessions.length}</div></div><div class="metric"><div class="label">Individual drill logs</div><div class="number">${drills.length}</div></div><div class="metric"><div class="label">Song notes</div><div class="number">${songs.length}</div></div></div>
 <div class="grid-2"><div class="card"><div class="card-header"><h2>Key coverage</h2>${tag('Circle of fourths')}</div><div class="key-grid">${KEYS.map(k=>`<div class="key-tile ${keys[k]?'past':''}" title="${keys[k]} sessions">${k.replace('b','♭')}<div class="micro muted">${keys[k]}×</div></div>`).join('')}</div><p class="footnote">Counts represent completed practice sessions, not mastery in a key.</p></div>
 <div class="card"><div class="card-header"><h2>Top clean tempos</h2>${tag('By drill + key + subdivision')}</div>${bars.length?bars.map(([k,v])=>`<div class="bar-chart"><label title="${safe(k)}">${safe(k)}</label><div class="bar-bg"><div style="width:${v/max*100}%"></div></div><strong>${v} BPM</strong></div>`).join(''):'<div class="empty">No clean drill ratings yet. Your progress will appear here after practice.</div>'}<p class="footnote">Only compare the same drill, key and rhythmic subdivision; your ratings are self-assessed.</p></div></div>
 <div class="grid-2" style="margin-top:18px"><div class="card"><div class="card-header"><h2>Most reported issues</h2>${tag('All-time')}</div>${Object.keys(issues).length?Object.entries(issues).sort((a,b)=>b[1]-a[1]).map(([label,n])=>`<div class="step-row"><div class="step-info"><div class="step-name">${safe(label)}</div></div><strong>${n}</strong></div>`).join(''):'<p>No issues recorded.</p>'}</div>
 <div class="card"><h2>Weekly report</h2><p>Export a concise text report for ChatGPT, and keep a complete local backup. Nothing is automatically sent to ChatGPT.</p><div class="buttons">${btn('copy-weekly',`${ic('check')} Copy 7-day report`,'primary')}${btn('download-weekly',`${ic('download')} Download .md`)}<a href="https://chatgpt.com/" target="_blank" rel="noopener noreferrer" class="btn ghost">Open ChatGPT ↗</a></div><div class="divider"></div><div class="buttons">${btn('export-json','Full JSON backup')}${btn('export-csv','CSV spreadsheet')}</div></div></div>
 <div class="card" style="margin-top:18px"><div class="card-header"><h2>Recent drill results</h2>${tag('Latest 30')}</div>${drills.length?`<div style="overflow-x:auto"><table class="table"><thead><tr><th>Date</th><th>Exercise</th><th>Key</th><th>Tempo</th><th>Assessment</th><th>Issue</th></tr></thead><tbody>${drills.slice(0,30).map(r=>`<tr><td class="nowrap">${new Date(r.created_at).toLocaleDateString()}</td><td>${safe(DRILL_BY_ID[r.payload?.drillId]?.title||r.payload?.drillId||'Song practice')}</td><td>${safe(r.payload?.key)}</td><td>${safe(r.payload?.bpm||'—')}</td><td>${safe(r.payload?.rating||'—')}</td><td>${safe(r.payload?.issue||'—')}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">Your first drill result will appear here once you finish and rate an exercise.</div>'}</div>`;}
function renderSettings(){return `${pageHeader('Configuration','Settings & cloud','Local-first. Cloud sync is optional and requires your own free Supabase project.')}
 <div class="grid-main"><div><div class="card"><div class="card-header"><h2>Display & metronome</h2>${ic('settings')}</div><div class="form-row"><div class="form-group"><label>Theme</label><select data-setting="theme"><option value="dark" ${state.settings.theme==='dark'?'selected':''}>Dark</option><option value="light" ${state.settings.theme==='light'?'selected':''}>Light</option></select></div><div class="form-group"><label>Default BPM</label><input type="number" id="setting-bpm" class="field" min="30" max="240" value="${state.settings.defaultBpm}"/></div></div><div class="buttons" style="margin-top:12px">${btn('save-bpm','Save default BPM')}</div><p class="footnote">All drills can be used without an account or internet access after the site has been cached.</p></div>
 <div class="card" style="margin-top:18px"><div class="card-header"><h2>Supabase cloud sync</h2>${ic('cloud')}</div><p><strong>For Mac, Windows and iPhone sync.</strong> Create a free Supabase project, run the provided SQL schema, then use its Project URL and public publishable/anon key below. Never use a secret/service_role key.</p><div class="form-group"><label for="cloud-url">Project URL</label><input class="field" id="cloud-url" autocomplete="off" placeholder="https://your-project.supabase.co" value="${safe(state.cloud.url||'')}"/></div><div class="form-group" style="margin-top:12px"><label for="cloud-key">Publishable / anon key (public)</label><input class="field" id="cloud-key" autocomplete="off" placeholder="sb_publishable_… or legacy eyJ…" value="${safe(state.cloud.key||'')}"/></div><div class="buttons" style="margin-top:14px">${btn('cloud-config-save','Save cloud settings','primary')}${btn('cloud-sync',`${ic('refresh')} Sync now`)}</div><p id="cloud-status" class="status ${cloudKind}" style="margin-top:12px">${safe(cloudMessage)}</p><div class="divider"></div>
 ${cloud.user?`<p class="small"><strong>Signed in:</strong> ${safe(cloud.user.email||cloud.user.id)}</p>${btn('cloud-sign-out','Sign out','ghost')}`:`<div class="form-row"><div class="form-group"><label>Email for sign-in link</label><input type="email" id="cloud-email" class="field" placeholder="you@example.com"/></div>${btn('cloud-login','Send magic link','primary')}</div><p class="footnote">Configure the exact GitHub Pages URL under Supabase Authentication → URL Configuration → Redirect URLs. A new device will need you to open the same site and sign in.</p>`}
 <div class="alert" style="margin-top:16px">Free Supabase projects can pause if insufficiently active. When sync fails, local practice records are retained; resume your project in Supabase and press Sync now.</div></div>
 <div class="card" style="margin-top:18px"><h2>Backups & restoration</h2><p>Keep periodic JSON backups. Import merges by record ID, so the same record is not duplicated.</p><div class="buttons">${btn('export-json',`${ic('download')} Download JSON`)}${btn('export-csv','Download CSV')}</div><div class="form-group" style="margin-top:14px"><label for="import-file">Import previous JSON backup</label><input type="file" class="field" accept="application/json,.json" id="import-file"/></div><p class="footnote">Import adds historical records; it doesn't erase existing records. Local in-progress sessions are not synchronized until completed.</p></div></div>
 <aside><div class="card"><div class="eyebrow">Your data</div><h2 style="margin-top:12px">Small, portable, private</h2><p>Practice logs and song notes are stored in your browser first. When signed in, they are copied to your own Supabase table with row-level security.</p><div class="divider"></div><p>GitHub Pages hosts only the code. It does not store private performance results.</p><p>For cloud access, use the same email login on every device. The URL and publishable key can be prefilled in <code>config.js</code> so you configure them only once.</p><div class="divider"></div><p class="small">Version ${APP_VERSION} · No analytics trackers · No paid API dependencies</p></div></aside></div>`;}

class Metronome{
 constructor(){this.playing=false;this.ctx=null;this.handle=null;this.nextBeat=0;this.beat=0;}
 async toggle(){if(this.playing){this.stop();return;}try{const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio)throw Error('Web Audio unavailable.');this.ctx=this.ctx||new Audio();await this.ctx.resume();this.playing=true;this.beat=0;this.nextBeat=this.ctx.currentTime+.08;this.handle=setInterval(()=>this.schedule(),25);this.schedule();}catch(err){showToast('Cannot start audio: '+err.message);this.stop();}}
 click(at,accent=false,soft=false){const osc=this.ctx.createOscillator(),gain=this.ctx.createGain();osc.type='sine';osc.frequency.setValueAtTime(accent?1100:soft?610:850,at);gain.gain.setValueAtTime(0.0001,at);gain.gain.exponentialRampToValueAtTime(soft?.10:.22,at+.005);gain.gain.exponentialRampToValueAtTime(.0001,at+.065);osc.connect(gain).connect(this.ctx.destination);osc.start(at);osc.stop(at+.073);}
 schedule(){if(!this.ctx||!this.playing)return;const bpm=Math.max(30,Math.min(240,Number(state.settings.defaultBpm)||70)),sub=state.settings.subdivision,compound=state.settings.meter==='6/8';const duration=60/bpm;let loop=0;
 while(this.nextBeat<this.ctx.currentTime+.16&&loop++<12){const accent=this.beat%(compound?2:4)===0;this.click(this.nextBeat,accent);
  if(sub==='swing'&&!compound)this.click(this.nextBeat+duration*2/3,false,true);
  if(sub==='triplet'||(compound&&sub==='quarter')){this.click(this.nextBeat+duration/3,false,true);this.click(this.nextBeat+duration*2/3,false,true);}
  this.nextBeat+=duration;this.beat++;}}
 stop(){if(this.handle)clearInterval(this.handle);this.handle=null;this.playing=false;}
}
const metronome=new Metronome();
function changeTempo(n){const bpm=Math.min(240,Math.max(30,Number(state.settings.defaultBpm)+n));state.settings.defaultBpm=bpm;saveState(state);const value=$('current-bpm');if(value)value.textContent=bpm; if(metronome.playing){metronome.stop();}render();}
function pauseTimer(){if(state.active?.startedAt){state.active.elapsedMs=Math.max(0,(state.active.elapsedMs||0)+Date.now()-state.active.startedAt);state.active.startedAt=null;saveState(state);}}
function toggleTimer(){const a=state.active;if(!a)return;if(a.startedAt){pauseTimer();}else{a.startedAt=Date.now();saveState(state);}render();}
function startSession(isFree=false,drillId=null,songId=null){if(state.active){setRoute('practice');return;}const mode=state.settings.selectedMode,day=countSessions();const a=makeSession(day,mode,state.settings.selectedSong);a.isFree=isFree;
 if(state.settings.selectedKey!=='auto')a.key=state.settings.selectedKey;
 if(isFree){a.entries=[{id:drillId||'song',minutes:drillId?DRILL_BY_ID[drillId].minutes:12,done:false}];a.songId=songId||a.songId;}
 state.active=a;saveState(state);showRating=false;diagramStep=-1;setRoute('practice');}
function finishCurrent(rating,issue){const a=state.active,entry=currentDrill();if(!entry)return;pauseTimer();metronome.stop();const drillId=entry.id==='song'?`song:${a.songId}`:entry.id;
 const p={sessionId:a.id,drillId,key:a.key,bpm:Number(state.settings.defaultBpm),rating,issue:issue||'none',seconds:Math.round(clockMs()/1000),subdivision:state.settings.subdivision,position:state.settings.position,meter:state.settings.meter,mode:a.mode,dayNumber:a.dayNumber};addRecord(state,'drill',p);
 if(entry.id==='song'){const previous=latestSong(a.songId)||{};addRecord(state,'song',{...previous,songId:a.songId,readiness:previous.readiness||'developing',notes:[previous.notes,'Practice session: '+rating].filter(Boolean).join(' | '),minutes:entry.minutes,fromSession:true});}
 entry.done=true;entry.rating=rating;entry.bpm=p.bpm;entry.seconds=p.seconds;a.position++;a.elapsedMs=0;a.startedAt=null;saveState(state);showRating=false;diagramStep=-1;cloud.sync();render();}
function finishEarly(){if(!state.active)return;pauseTimer();metronome.stop();state.active.position=state.active.entries.length;saveState(state);render();}
function saveCompletedSession(){const a=state.active;if(!a)return;pauseTimer();metronome.stop();a.notes=$('session-notes')?.value?.trim()||'';const seconds=a.entries.reduce((total,x)=>total+(x.seconds||0),0);addRecord(state,'session',{sessionId:a.id,key:a.key,mode:a.mode,dayNumber:a.dayNumber,songId:a.songId,drillsCompleted:a.entries.filter(x=>x.done).length,drillsPlanned:a.entries.length,durationMinutes:Math.round(seconds/60),notes:a.notes,isFree:a.isFree});state.active=null;saveState(state);cloud.sync();showToast('Session saved. Your next key is ready.');setRoute('progress');}
function saveSong(id){const s=SONGS.find(x=>x.id===id);if(!s)return;const tempo=Number($('song-tempo')?.value||0);const key=$('song-key')?.value?.trim()?.slice(0,12)||'';const notes=$('song-notes')?.value?.trim()||'';const readiness=$('song-readiness')?.value||'learning';const sections=[...document.querySelectorAll('input[data-song-section]:checked')].map(x=>x.dataset.songSection);
 addRecord(state,'song',{songId:id,key,tempo:tempo>=30&&tempo<=260?tempo:null,readiness,sections,notes});cloud.sync();showToast('Song profile saved');render();}
function exportJson(){const data={app:'Guitar Practice Lab',version:APP_VERSION,exportedAt:new Date().toISOString(),records:state.records,settings:state.settings};downloadText(`guitar-practice-lab-backup-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(data,null,2),'application/json');}
async function copyWeekly(){const report=weeklyReport(state);try{await navigator.clipboard.writeText(report);showToast('7-day report copied. Paste it into ChatGPT.');}catch{downloadWeekly();showToast('Clipboard unavailable. Downloaded report instead.');}}
function downloadWeekly(){downloadText(`guitar-practice-weekly-${new Date().toISOString().slice(0,10)}.md`,weeklyReport(state),'text/markdown');}
const actions={
 'start-session':()=>startSession(), 'resume-session':()=>setRoute('practice'),'toggle-timer':toggleTimer,'tempo-up':()=>changeTempo(5),'tempo-down':()=>changeTempo(-5),
 'metro-toggle':async()=>{await metronome.toggle();const label=$('metro-label');if(label)label.textContent=metronome.playing?'Stop click':'Metronome';},
 'rating-open':()=>{pauseTimer();showRating=true;render();},'rating-cancel':()=>{showRating=false;render();},
 'rate-clean':()=>finishCurrent('clean',$('drill-issue')?.value), 'rate-almost':()=>finishCurrent('almost',$('drill-issue')?.value), 'rate-retry':()=>finishCurrent('retry',$('drill-issue')?.value),
 'skip-drill':()=>{pauseTimer();metronome.stop();if(state.active){state.active.position++;state.active.startedAt=null;state.active.elapsedMs=0;saveState(state);render();}},
 'end-early':finishEarly,'save-session':saveCompletedSession,'resume-last':()=>{const a=state.active;if(a){a.position=Math.max(0,a.entries.length-1);saveState(state);render();}},
 'diagram-tab':()=>{state.settings.diagram='tab';saveState(state);render();},'diagram-fretboard':()=>{state.settings.diagram='fretboard';saveState(state);render();},
 'labels-note':()=>{state.settings.labels='note';saveState(state);render();},'labels-interval':()=>{state.settings.labels='interval';saveState(state);render();},'labels-hidden':()=>{state.settings.labels='hidden';saveState(state);render();},
 'step-next':()=>{const d=DRILL_BY_ID[currentDrill()?.id];const count=buildExample(d.kind,state.active.key,d.quality||'maj7',d.octaves||2,state.settings.position).length;diagramStep=Math.min(count-1,diagramStep+1);render();},
 'step-prev':()=>{diagramStep=Math.max(-1,diagramStep-1);render();},
 'copy-weekly':copyWeekly,'download-weekly':downloadWeekly,'export-json':exportJson,'export-csv':()=>downloadText(`guitar-practice-${new Date().toISOString().slice(0,10)}.csv`,exportCsv(state),'text/csv;charset=utf-8'),
 'save-bpm':()=>{const value=Number($('setting-bpm')?.value);if(value<30||value>240){showToast('Choose between 30 and 240 BPM');return;}state.settings.defaultBpm=value;saveState(state);showToast('Default tempo saved');render();},
 'cloud-config-save':async()=>{state.cloud.url=$('cloud-url')?.value?.trim()||'';state.cloud.key=$('cloud-key')?.value?.trim()||'';saveState(state);cloud.client=null;cloud.user=null;await cloud.init();showToast('Cloud configuration stored on this device.');render();},
 'cloud-login':async()=>{try{await cloud.signIn($('cloud-email')?.value?.trim()||'');render();}catch(err){cloud.status('Sign-in failed: '+err.message,'error');showToast(err.message);}},
 'cloud-sign-out':async()=>{try{await cloud.signOut();render();}catch(err){showToast(err.message);}},
 'cloud-sync':async()=>{if(!cloud.client)await cloud.init();if(!cloud.user){showToast('Sign in before syncing.');return;}await cloud.sync();render();}
};
document.addEventListener('click',async ev=>{const btn=ev.target.closest('[data-action]');if(!btn)return;ev.preventDefault();const name=btn.dataset.action;if(name?.startsWith('start-free:'))return startSession(true,name.slice(11));if(name?.startsWith('song-focus:'))return startSession(true,null,name.slice(11));if(name?.startsWith('save-song:'))return saveSong(name.slice(10));const handler=actions[name];if(handler){try{await handler();}catch(error){console.error(error);showToast('Action failed: '+error.message);}}});
document.addEventListener('change',async ev=>{const el=ev.target;if(el.dataset.setting){let value=el.value;if(el.dataset.setting==='selectedMode'&&state.active)return;state.settings[el.dataset.setting]=value;saveState(state);if(el.dataset.setting==='theme')document.body.dataset.theme=value;render();if(['subdivision','meter'].includes(el.dataset.setting)&&metronome.playing)metronome.stop();}
 if(el.id==='import-file'&&el.files?.[0]){try{const file=el.files[0];if(file.size>25_000_000)throw Error('File is larger than 25 MB.');const json=JSON.parse(await file.text());const added=importedSnapshot(state,json);showToast(`${added} records imported. Existing records preserved.`);cloud.sync();render();}catch(error){showToast('Import failed: '+error.message);}}
 if(el.id==='drill-category')filterDrills();});
document.addEventListener('input',ev=>{if(ev.target.id==='drill-search')filterDrills();if(ev.target.id==='session-notes'&&state.active){state.active.notes=ev.target.value;saveState(state);}});
function filterDrills(){const q=($('drill-search')?.value||'').trim().toLowerCase(),cat=$('drill-category')?.value||'all';document.querySelectorAll('.drill-search-row').forEach(row=>{row.classList.toggle('hide',!row.dataset.search.includes(q)||(cat!=='all'&&row.dataset.category!==cat));});}
window.addEventListener('hashchange',()=>{showRating=false;diagramStep=-1;render();});
document.addEventListener('visibilitychange',()=>{if(document.hidden){pauseTimer();metronome.stop();}});
window.addEventListener('beforeunload',()=>{pauseTimer();metronome.stop();});
setInterval(()=>{updateClock();if(state.active?.startedAt)saveState(state);},1000);
setInterval(()=>{if(cloud.user&&!document.hidden)cloud.sync();},120000);
render();if(cloud.configured)cloud.init();
if('serviceWorker' in navigator&&location.protocol==='https:'){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(err=>console.info('Offline cache not installed',err)));}
